# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tonarede.net.br
title: Pedro Reis
email: pedroreis.ti@gmail.com
author: Pedro Reis
description: > # "Esta será minha página pessoal para falar sobre assuntos do cotidiano e preferencialmente a conteúdos relacionado a TI & Telecom.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/PedroUFT
  - title: github
    url: https://github.com/pedroreisbr
  - title: linkedin
    url: https://www.linkedin.com/pub/pedro-henrique-silva-mendes-dos-reis/b1/972/480
  - title: facebook
    url: https://www.facebook.com/pedroreis.uft
