#######################################
# Este arquivo contém as flags de     #
# configuração para personalização    #
# do site                             #
#######################################

# ----------------------------------- #
#      Configurações Principais       #
# ----------------------------------- #

# O nome do site (exibido no cabeçalho)
title: PK - Pedro Reis
name: PK - Pedro Reis

# Url do site (usado para Sitemap.xml e feed RSS)
url: http://pedroreis.com.br
# Uma pequena biografia ou descrição do site (exibido no cabeçalho)
description: > # Esta será a página pessoal de PK onde será discutido
  assuntos do cotidiano e preferencialmente a conteúdos relacionado 
  a TI & Telecom.


# ----------------------------------- #
#      Informações Pessoais           #
# ----------------------------------- #  
email: pedroreis.ti@gmail.com
author: Pedro Reis

# Uma URL que aponta para avatar
avatar: http://www.gravatar.com/avatar/9a20cef56f9e1bfcd96c6e83c166ac14?s=200

# Url dos perfis para redes sociais
social:
  - title: twitter
    url: https://twitter.com/PedroUFT
  - title: linkedin
    url: https://www.linkedin.com/pub/pedro-henrique-silva-mendes-dos-reis/b1/972/480
  - title: facebook
    url: https://www.facebook.com/pedroreis.uft
  - title: instagram
    url: https://instagram.com/pedroreis_ti/
  - title: github
    url: https://github.com/pedroreisbr
  # - title: dribbble
  #   url: https://
  # - title: email
  #   url: https://
  # - title: flickr
  #   url: https://
  # - title: pinterest
  #   url: https://
  # - title: rss
  #   url: https://

# ----------------------------------- #
#      Configurações Página           #
# ----------------------------------- #

# O nome de usuário Disqus, para permitir comentários nos posts
# disqus: pedroreisbr -- configurar

# Código de acompanhamento do Google Analytics Web para ativar o rastreamento
# google_analytics: UA-0000000-0 -- configurar

# Código para análise de dados com Gauges
# gauges_id: 000000000000000

# Uma subpath do site, ex. /blog/
# baseurl: "" 

# Link Repositorio GitHub
repository: https://github.com/pedroreisbr/pedroreisbr.github.io
#help_url: https://github.com/pedroreisbr/pedroreis-help

# Outras configurações
markdown: kramdown
highlighter: pygments

# Configuração link
#permalink: /news/:year/:month/:day/:title/
permalink: /:title

# Emoji
gems:
  - jemoji

# Arquivos para serem excluidos da construção _site
exclude:
    - Gemfile
    - Gemfile.lock
    - scss
    - README.md